version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=production
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
